import { ArrowUpRight } from 'lucide-react'
import { PageIntro, SectionHeading } from '../components/ui'
import { restaurantStats } from '../data/restaurantData'

const gallery = ['https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1000&q=85', 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1000&q=85', 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1000&q=85', 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=1000&q=85']

export default function About() {
  return <><PageIntro eyebrow="The Savoria story" title="Made with heart, served with intention." body="A neighbourhood restaurant with an Italian soul and a distinctly Delhi rhythm." /><section className="story section-pad"><div className="container story-grid"><div className="story-image"><img src="https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=1200&q=85" alt="Savoria dining room" /></div><div className="story-copy"><span className="eyebrow">Since 2012</span><h2>It started with a table for six.</h2><p>In 2012, Savoria began as a simple idea: create the kind of restaurant we wanted to spend time in. One with honest cooking, a room full of light and a welcome that felt personal.</p><p>Over a decade later, that idea still guides us. We bring the generous spirit of the Italian table to New Delhi, with ingredients and influences that travel a little further every season.</p><blockquote>“The best meals are not just eaten. They become part of the story.”<cite>— Matteo Rinaldi, founder & chef</cite></blockquote></div></div></section><section className="stats-band"><div className="container stats-grid">{restaurantStats.map(stat => <div key={stat.label}><strong>{stat.value}</strong><span>{stat.label}</span></div>)}</div></section><section className="philosophy section-pad"><div className="container philosophy-grid"><SectionHeading eyebrow="Our point of view" title="Good food is a conversation." /><div><p className="large-copy">We believe a restaurant should have a point of view, but never an ego. Our menus are expressive without being precious, our service is polished but never stiff, and every detail is considered to help you settle in.</p><p>From the first pour to the last spoonful, we want you to feel looked after. That is our version of luxury.</p></div></div></section><section className="gallery-section"><div className="container"><div className="heading-row"><SectionHeading eyebrow="A glimpse inside" title="The Savoria feeling" /><a href="https://instagram.com" className="text-link">Follow along <ArrowUpRight size={16} /></a></div><div className="gallery-grid">{gallery.map((image, index) => <img key={image} className={`gallery-image gallery-${index + 1}`} src={image} alt={`Savoria gallery moment ${index + 1}`} loading="lazy" />)}</div></div></section><section className="chef-feature section-pad"><div className="container chef-grid"><div><span className="eyebrow">Meet the chef</span><h2>“Food should<br /><em>make you feel.”</em></h2><p>Chef Matteo Rinaldi brings a love of Italian tradition, a respect for Indian ingredients and just enough mischief to every plate.</p><span className="signature">Matteo Rinaldi</span></div><img src="https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&w=1000&q=85" alt="Chef Matteo Rinaldi in the kitchen" /></div></section></>
}
