import { useState } from 'react'
import { ArrowUpRight, Camera, Users, Mail, MapPin, Phone } from 'lucide-react'
import { Button, PageIntro, Toast } from '../components/ui'
import { openingHours } from '../data/restaurantData'

export default function Contact() {
  const [sent, setSent] = useState(false)
  const submit = event => { event.preventDefault(); setSent(true); event.currentTarget.reset() }
  return <><PageIntro eyebrow="We would love to hear from you" title="Come say hello." body="Whether you are planning a special evening, have a question or simply want to talk food, our door is always open." /><section className="contact-section section-pad"><div className="container contact-grid"><div className="contact-details"><div className="contact-detail"><MapPin /><div><span>Visit us</span><strong>14, Amrita Shergill Marg<br />New Delhi 110003</strong><a href="https://maps.google.com" target="_blank" rel="noreferrer">Get directions <ArrowUpRight size={15} /></a></div></div><div className="contact-detail"><Phone /><div><span>Call us</span><a href="tel:+911141234567"><strong>+91 11 4123 4567</strong></a><small>Mon - Sun, 11 am - 10 pm</small></div></div><div className="contact-detail"><Mail /><div><span>Write to us</span><a href="mailto:hello@savoria.in"><strong>hello@savoria.in</strong></a><small>We usually reply within a day</small></div></div><div className="contact-social"><span>Follow the feeling</span><div><a href="https://instagram.com" aria-label="Instagram"><Camera /></a><a href="https://facebook.com" aria-label="Facebook"><Users /></a></div></div></div><form className="contact-form" onSubmit={submit}><span className="eyebrow">Send a message</span><label>Name<input name="name" required placeholder="Your name" /></label><label>Email<input type="email" name="email" required placeholder="you@example.com" /></label><label>How can we help?<select name="topic"><option>General enquiry</option><option>Private dining</option><option>Press & partnerships</option><option>Feedback</option></select></label><label>Your message<textarea name="message" required rows="5" placeholder="Tell us a little more..." /></label><Button type="submit">Send message</Button></form></div></section><section className="map-section"><div className="container map-grid"><div className="map-art"><div className="map-pin"><MapPin size={19} /></div><span className="map-label">Savoria</span><div className="map-road road-one" /><div className="map-road road-two" /><div className="map-road road-three" /></div><div className="map-copy"><span className="eyebrow">Find your way here</span><h2>In the heart of<br /><em>Lutyens' Delhi.</em></h2><p>A quiet, leafy corner just minutes from Khan Market and Lodhi Garden.</p><a href="https://maps.google.com" target="_blank" rel="noreferrer" className="text-link">Open in Google Maps <ArrowUpRight size={16} /></a></div></div></section><section className="hours-strip"><div className="container hours-strip-inner"><span className="eyebrow">Opening hours</span>{openingHours.map(item => <div key={item.day}><strong>{item.day}</strong><span>{item.hours}</span></div>)}</div></section>{sent && <Toast onClose={() => setSent(false)}><span>Your message has been sent. Thank you for reaching out.</span></Toast>}</>
}
