import { ArrowDown, Clock3, MapPin, Utensils } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Button, FoodCard, SectionHeading, TestimonialCard } from '../components/ui'
import { menuItems, testimonials } from '../data/restaurantData'

export default function Home() {
  return <>
    <section className="hero"><div className="hero-image" /><div className="hero-overlay" /><div className="container hero-content"><span className="eyebrow hero-eyebrow">Modern European kitchen · New Delhi</span><h1>Good food.<br /><em>Great moments.</em></h1><p>Thoughtful plates, warm hospitality and a little bit of magic at every table.</p><div className="hero-actions"><Button to="/menu">View the menu</Button><Button to="/reservations" variant="outline">Reserve a table</Button></div></div><div className="hero-scroll"><ArrowDown size={16} /> Scroll to explore</div><div className="hero-stamp"><span>Est.</span><strong>2012</strong><span>New Delhi</span></div></section>
    <section className="welcome section-pad"><div className="container welcome-grid"><div className="welcome-visual"><img src="https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=1200&q=85" alt="Warmly lit Savoria dining room" /><span className="image-note">The room, after dusk</span></div><div className="welcome-copy"><span className="eyebrow">A seat at our table</span><h2>A little corner of Italy, right in the heart of Delhi.</h2><p>Savoria is a neighbourhood restaurant with a worldly point of view. Our kitchen follows the seasons, our wine list follows curiosity, and our room is made for the kind of evenings that stay with you.</p><p>Come for the hand-rolled pasta. Stay for another glass.</p><Link to="/about" className="text-link">Discover our story <ArrowDown size={16} className="rotate-arrow" /></Link></div></div></section>
    <section className="featured section-pad section-soft"><div className="container"><div className="heading-row"><SectionHeading eyebrow="From the kitchen" title="Made to be shared" body="A few of the plates our guests return for, season after season." /><Link to="/menu" className="text-link desktop-link">See full menu <ArrowDown size={16} className="rotate-arrow" /></Link></div><div className="food-grid featured-grid">{menuItems.slice(0, 3).map(item => <FoodCard key={item.id} item={item} featured />)}</div><Link to="/menu" className="text-link mobile-link">See full menu <ArrowDown size={16} className="rotate-arrow" /></Link></div></section>
    <section className="manifesto section-pad"><div className="container manifesto-grid"><div><span className="eyebrow">Why Savoria</span><h2>Simple ingredients.<br /><em>Serious intention.</em></h2></div><div className="manifesto-points"><div><span className="point-number">01</span><div><h3>Cook with the seasons</h3><p>We work closely with small farms and makers across India, letting the best produce set the pace.</p></div></div><div><span className="point-number">02</span><div><h3>Make room for joy</h3><p>There are no rules here, just good food, generous pours and a table worth lingering at.</p></div></div><div><span className="point-number">03</span><div><h3>Leave things better</h3><p>Thoughtful sourcing and considered choices, from our kitchen to the last light in the dining room.</p></div></div></div></div></section>
    <section className="special section-pad"><div className="container special-grid"><div className="special-image"><img src="https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1300&q=85" alt="Chef's special seasonal plate" /><span className="special-label">This month at Savoria</span></div><div className="special-copy"><span className="eyebrow">Chef's special</span><h2>Wild mushroom<br /><em>risotto</em></h2><p>Slow-stirred Carnaroli, forest mushrooms, aged parmesan and a whisper of black truffle. Rich, earthy and made for the first cool evenings of the season.</p><div className="special-meta"><span>Vegetarian</span><span>₹1,095</span></div><Button to="/reservations" variant="text">Book the experience</Button></div></div></section>
    <section className="testimonials section-pad section-soft"><div className="container"><SectionHeading eyebrow="Kind words" title="The best part is hearing from you." align="center" /><div className="testimonial-grid">{testimonials.map(testimonial => <TestimonialCard key={testimonial.name} testimonial={testimonial} />)}</div></div></section>
    <section className="visit section-pad"><div className="container visit-grid"><div><SectionHeading eyebrow="Come by soon" title="Your table is waiting." body="Make an evening of it. We are open seven days a week for lunch, dinner and everything in between." /><Button to="/reservations">Reserve a table</Button></div><div className="visit-details"><div><Clock3 size={22} /><span>Opening hours</span><strong>Mon - Sun · 12 pm onwards</strong></div><div><MapPin size={22} /><span>Find us</span><strong>14, Amrita Shergill Marg<br />New Delhi 110003</strong></div><div><Utensils size={22} /><span>Good to know</span><strong>Walk-ins welcome<br />Reservations recommended</strong></div></div></div></section>
  </>
}
