import { useState } from 'react'
import { Check } from 'lucide-react'
import { Button, PageIntro, Toast } from '../components/ui'
import { openingHours } from '../data/restaurantData'

const initialForm = { name: '', email: '', phone: '', guests: '2 guests', date: '', time: '', requests: '' }

export default function Reservations() {
  const [form, setForm] = useState(initialForm)
  const [submitted, setSubmitted] = useState(false)
  const [error, setError] = useState('')
  const update = event => setForm({ ...form, [event.target.name]: event.target.value })
  const submit = event => { event.preventDefault(); if (!form.name || !form.email || !form.phone || !form.date || !form.time) { setError('Please complete the required fields to request your table.'); return } setError(''); setSubmitted(true); setForm(initialForm) }
  return <><PageIntro eyebrow="Make an evening of it" title="Reserve your table" body="Tell us when you would like to join us. We will confirm your reservation by email within 24 hours." /><section className="reservation-section section-pad"><div className="container reservation-grid"><div className="reservation-form-wrap"><div className="form-top"><span className="eyebrow">Your details</span><span className="required-note">* Required</span></div><form className="reservation-form" onSubmit={submit} noValidate><div className="form-grid"><label>Full name *<input name="name" value={form.name} onChange={update} placeholder="Your name" /></label><label>Email address *<input type="email" name="email" value={form.email} onChange={update} placeholder="you@example.com" /></label><label>Phone number *<input type="tel" name="phone" value={form.phone} onChange={update} placeholder="+91 00000 00000" /></label><label>Number of guests<select name="guests" value={form.guests} onChange={update}><option>1 guest</option><option>2 guests</option><option>3 guests</option><option>4 guests</option><option>5+ guests</option></select></label><label>Date *<input type="date" name="date" value={form.date} onChange={update} min={new Date().toISOString().split('T')[0]} /></label><label>Preferred time *<select name="time" value={form.time} onChange={update}><option value="">Select a time</option><option>12:30 PM</option><option>1:30 PM</option><option>7:30 PM</option><option>8:30 PM</option><option>9:30 PM</option></select></label></div><label>Special requests <textarea name="requests" value={form.requests} onChange={update} placeholder="Dietary requirements, celebrations, seating preferences..." rows="4" /></label>{error && <p className="form-error">{error}</p>}<Button type="submit">Request reservation</Button><small className="form-footnote">Please note: your table is confirmed once you receive our email.</small></form></div><aside className="reservation-aside"><div className="aside-image"><img src="https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1000&q=85" alt="Savoria's candlelit dining room" /></div><div className="hours-card"><span className="eyebrow">When to find us</span>{openingHours.map(item => <div key={item.day}><span>{item.day}</span><strong>{item.hours}</strong></div>)}<p>For parties of 7 or more, please <a href="mailto:hello@savoria.in">contact us directly.</a></p></div></aside></div></section>{submitted && <Toast onClose={() => setSubmitted(false)}><span>Reservation request received. We will be in touch soon.</span><Check size={15} /></Toast>}</>
}
